# -*- coding: utf-8 -*-
"""Laborator10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IbAHMgxhjiyVfmZhQBQhsdGYkLHsvtS-
"""

import numpy as np
import pymc as pm
import arviz as az
import matplotlib.pyplot as plt

publicity = np.array([
    1.5, 2.0, 2.3, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0,
    6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0, 10.5, 11.0
])

sales = np.array([
    5.2, 6.8, 7.5, 8.0, 9.0, 10.2, 11.5, 12.0, 13.5, 14.0,
    15.0, 15.5, 16.2, 17.0, 18.0, 18.5, 19.5, 20.0, 21.0, 22.0
])

new_publicity = np.array([12.0, 15.0])

with pm.Model() as model:
    alpha = pm.Normal("alpha", mu=0, sigma=20)
    beta = pm.Normal("beta", mu=0, sigma=10)
    sigma = pm.HalfNormal("sigma", sigma=5)

    mu = alpha + beta * publicity

    pm.Normal("sales", mu=mu, sigma=sigma, observed=sales)

    idata = pm.sample(2000, tune=1000, target_accept=0.9, random_seed=1)

print("\n--- HDI Coeficienti (95%) ---")
coef_hdi = az.hdi(idata, var_names=["alpha", "beta"], hdi_prob=0.95)
print(coef_hdi)

posterior_alpha = idata.posterior['alpha'].values.flatten()
posterior_beta = idata.posterior['beta'].values.flatten()
posterior_sigma = idata.posterior['sigma'].values.flatten()

plt.figure(figsize=(10, 6))
plt.scatter(publicity, sales, c='black', label='Date observate')

x_plot = np.linspace(0, 16, 100)
mean_alpha = posterior_alpha.mean()
mean_beta = posterior_beta.mean()
y_mean = mean_alpha + mean_beta * x_plot

for i in range(50):
    y_sample = posterior_alpha[i] + posterior_beta[i] * x_plot
    plt.plot(x_plot, y_sample, c='blue', alpha=0.1)

plt.plot(x_plot, y_mean, c='red', label='Regresie medie')
plt.xlabel("Cheltuieli Publicitate")
plt.ylabel("Vanzari")
plt.legend()
plt.title("Regresie Liniara: Predictii Grafice")
plt.show()

print("\n--- Predictii Vanzari (Interval 90%) ---")

rng = np.random.default_rng(1)
n_samples = len(posterior_alpha)

for val in new_publicity:
    mu_pred = posterior_alpha + posterior_beta * val
    y_pred_dist = rng.normal(mu_pred, posterior_sigma)

    lo, hi = np.percentile(y_pred_dist, [5, 95])
    print(f"Publicitate: {val} => Vanzari estimate intre {lo:.2f} si {hi:.2f}")