# -*- coding: utf-8 -*-
"""Laborator14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jVKLv5cwGCxgmBQ23uAGhhOw_yPx2o4s
"""

import numpy as np
import pandas as pd
import pymc as pm
import arviz as az
import pytensor.tensor as pt
import matplotlib.pyplot as plt

df = pd.read_csv("date_colesterol.csv")
t = df["Ore_Exercitii"].to_numpy()
y_obs = df["Colesterol"].to_numpy()
t2 = t**2

Ks = [3, 4, 5]
idatas = {}

t_ref = float(t.mean())
t2_ref = t_ref**2

for K in Ks:
    with pm.Model() as model:
        p = pm.Dirichlet("p", a=np.ones(K) * 4.0)

        alpha = pm.Normal(
            "alpha",
            mu=np.linspace(y_obs.min(), y_obs.max(), K),
            sigma=50,
            shape=K,
        )
        beta = pm.Normal("beta", mu=0, sigma=20, shape=K)
        gamma = pm.Normal("gamma", mu=0, sigma=10, shape=K)

        sd = pm.HalfNormal("sd", sigma=30, shape=K)

        means_ref = alpha + beta * t_ref + gamma * t2_ref
        pm.Potential(
            "order_means",
            pt.switch(pt.any(means_ref[1:] - means_ref[:-1] < 0), -np.inf, 0.0),
        )

        # media pentru fiecare observatie (N x K)
        mu = alpha + beta * t[:, None] + gamma * t2[:, None]

        y = pm.NormalMixture("y", w=p, mu=mu, sigma=sd, observed=y_obs)

        idata = pm.sample(
            draws=1000,
            tune=2000,
            target_accept=0.9,
            chains=4,
            cores=1,
            random_seed=123,
            return_inferencedata=True,
        )

        idata = pm.compute_log_likelihood(idata, model=model)

    idatas[str(K)] = idata

# 1.1)
for K in Ks:
    k = str(K)
    print("\nK =", K)
    print(az.summary(idatas[k], var_names=["p", "alpha", "beta", "gamma", "sd"]))

# 1.2) comparatie WAIC / LOO + grafice
comp_waic = az.compare(idatas, ic="waic", method="BB-pseudo-BMA", scale="deviance")
comp_loo  = az.compare(idatas, ic="loo",  method="BB-pseudo-BMA", scale="deviance")

print("\nWAIC comparison:")
print(comp_waic)

print("\nLOO comparison:")
print(comp_loo)

az.plot_compare(comp_waic)
plt.title("Model comparison by WAIC")
plt.show()

az.plot_compare(comp_loo)
plt.title("Model comparison by LOO")
plt.show()

print("\nBest by WAIC:", comp_waic.index[0])
print("Best by LOO:",  comp_loo.index[0])