# -*- coding: utf-8 -*-
"""Laborator12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ShfVcya0dJ8uJFKHS-KEcmaWa24BRTY
"""

import numpy as np
import pandas as pd
import pymc as pm
import arviz as az
import matplotlib.pyplot as plt

#a
df = pd.read_csv("date_promovare_examen.csv")

x1 = df["Ore_Studiu"].values
x2 = df["Ore_Somn"].values
y  = df["Promovare"].values

print("Balansare clase:")
print(df["Promovare"].value_counts())

X = df[["Ore_Studiu", "Ore_Somn"]].values

with pm.Model() as model:
    alpha = pm.Normal("alpha", mu=0, sigma=10)
    beta = pm.Normal("beta", mu=0, sigma=2, shape=2)

    μ = alpha + pm.math.dot(X, beta)
    θ = pm.Deterministic("θ", 1 / (1 + pm.math.exp(-μ)))

    bd = pm.Deterministic("bd", -alpha/beta[1] - (beta[0]/beta[1]) * X[:, 0])

    yl = pm.Bernoulli("yl", p=θ, observed=y)

    idata = pm.sample(2000, target_accept=0.9, return_inferencedata=True)

#b
a_mean = idata.posterior["alpha"].mean(("chain", "draw")).values
b_mean = idata.posterior["beta"].mean(("chain", "draw")).values

print("\nMediile estimarilor:")
print("alpha =", float(a_mean))
print("beta =", b_mean)

x_grid = np.linspace(x1.min(), x1.max(), 100)
sleep_line = -a_mean/b_mean[1] - (b_mean[0]/b_mean[1]) * x_grid

plt.scatter(x1, x2, c=y)
plt.plot(x_grid, sleep_line, "k")
plt.xlabel("Ore_Studiu / saptamana")
plt.ylabel("Ore_Somn / zi")
plt.show()

#Sunt datele bine separate? (clasificare cu prag 0.5)
p = 1 / (1 + np.exp(-(a_mean + b_mean[0]*x1 + b_mean[1]*x2)))
y_pred = (p > 0.5).astype(int)
acc = (y_pred == y).mean()
print("\nAcuratetea(cu media posteriorului):", acc)

#c
print(az.hdi(idata.posterior[["beta"]], hdi_prob=0.95))
print(az.summary(idata, var_names=["beta"]))

'''
Coeficientul pentru orele de somn este mai mare decat cel pentru orele de studiu.
De asemenea, intervalul HDI este mai indepartat de zero.
Acest lucru arata ca orele de somn au o influenta mai mare asupra promovarii.
'''